name: MysteryUniverse
version: ${project.version}
main: com.mysteria.mysteryuniverse.MysteryUniversePlugin
api-version: 1.16
authors: [ Singularity ]
depend: [ LuckPerms, MysteriaUtils, WorldEdit, WorldGuard, MysteriaParry, ProtocolLib, CustomAPI, MysteriaPlayerTitles ]